// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnttyqgbovtgqashutjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudHR5cWdib3Z0Z3Fhc2h1dGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzU5NTcsImV4cCI6MjA3MDA1MTk1N30.eg6cqKEPv_JGALLFv8ePpzyx3YUjPmoI3E5q-LCXsN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});